version: '3.2'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'queue-service'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${AMQP_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${AMQP_PASSWORD}
    volumes:
      - ~/.docker-conf/rabbitmq/data/:${PROJECT_PATH}/Docker/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:${PROJECT_PATH}/Docker/log/rabbitmq
    networks:
      - rabbitmq_api_queue_net

  api-queue:
    container_name: nodejs-service
    image: node:18
    working_dir: ${PROJECT_PATH}/Docker/discord-bot-api-queue
    restart: always
    command: bash -c "npm install --force && npm run debug"
    environment:
      - AMQP_USERNAME=discord-bot-api-queue
      - AMQP_PASSWORD=password
      - AMQP_PORT=5672
      - AMQP_ADRESS=rabbitmq
      - BOT_API_URL=http://localhost:5050/api
      - BOT_API_TOKEN={$BOT_API_TOKEN}
      - DISCORD_APPLICATION_ID={$DISCORD_APPLICATION_ID}
      - DISCORD_API_URL={$DISCORD_API_URL}
      - DISCORD_BOT_TOKEN={$DISCORD_BOT_TOKEN}
      - PROJECT_PATH={$PROJECT_PATH}
    volumes:
      - ./dist/:${PROJECT_PATH}/Docker/discord-bot-api-queue/dist
      - ./package.json:${PROJECT_PATH}/Docker/discord-bot-api-queue/package.json
    ports:
      - '4050:4050'
      - '8222:8222'
    links:
      - rabbitmq
    networks:
      - rabbitmq_api_queue_net

networks:
  rabbitmq_api_queue_net:
    driver: bridge
